app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

//Cache::flush();
//apc_clear_cache();
//dd(DB::getQueryLog());
//dd(Client::getPrivateId(1));
//dd(new DateTime());
//dd(App::environment());
//dd(gethostname());
//Log::error('test');

// Application setup
Route::get('setup', 'AppController@showSetup');
Route::post('setup', 'AppController@doSetup');
Route::get('install', 'AppController@install');
Route::get('update', 'AppController@update');

// Public pages
Route::get('/', 'HomeController@showIndex');
Route::get('terms', 'HomeController@showTerms');
Route::get('log_error', 'HomeController@logError');
Route::get('invoice_now', 'HomeController@invoiceNow');
Route::post('get_started', 'AccountController@getStarted');

// Client visible pages
Route::get('view/{invitation_key}', 'InvoiceController@view');
Route::get('approve/{invitation_key}', 'QuoteController@approve');
Route::get('payment/{invitation_key}/{payment_type?}', 'PaymentController@show_payment');
Route::post('payment/{invitation_key}', 'PaymentController@do_payment');
Route::get('complete', 'PaymentController@offsite_payment');
Route::get('client/quotes', 'QuoteController@clientIndex');
Route::get('client/invoices', 'InvoiceController@clientIndex');
Route::get('client/payments', 'PaymentController@clientIndex');
Route::get('api/client.quotes', array('as'=>'api.client.quotes', 'uses'=>'QuoteController@getClientDatatable'));
Route::get('api/client.invoices', array('as'=>'api.client.invoices', 'uses'=>'InvoiceController@getClientDatatable'));
Route::get('api/client.payments', array('as'=>'api.client.payments', 'uses'=>'PaymentController@getClientDatatable'));

Route::get('license', 'PaymentController@show_license_payment');
Route::post('license', 'PaymentController@do_license_payment');
Route::get('claim_license', 'PaymentController@claim_license');

Route::post('signup/validate', 'AccountController@checkEmail');
Route::post('signup/submit', 'AccountController@submitSignup');


// Laravel auth routes
/*
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);
*/

get('/signup', array('as' => 'signup', 'uses' => 'Auth\AuthController@getRegister'));
post('/signup', array('as' => 'signup', 'uses' => 'Auth\AuthController@postRegister'));
get('/login', array('as' => 'login', 'uses' => 'Auth\AuthController@getLogin'));
post('/login', array('as' => 'login', 'uses' => 'Auth\AuthController@postLoginWrapper'));
get('/logout', array('as' => 'logout', 'uses' => 'Auth\AuthController@getLogout'));
get('/forgot', array('as' => 'forgot', 'uses' => 'Auth\PasswordController@getEmail'));
post('/forgot', array('as' => 'forgot', 'uses' => 'Auth\PasswordController@postEmail'));
get('/password/reset', array('as' => 'forgot', 'uses' => 'Auth\PasswordController@getReset'));
post('/password/reset', array('as' => 'forgot', 'uses' => 'Auth\PasswordController@postReset'));
get('/user/confirm/{code}', 'UserController@confirm');

/*
// Confide routes
Route::get('login', 'UserController@login');
Route::post('login', 'UserController@do_login');
Route::get('forgot_password', 'UserController@forgot_password');
Route::post('forgot_password', 'UserController@do_forgot_password');
Route::get('user/reset/{token?}', 'UserController@reset_password');
Route::post('user/reset', 'UserController@do_reset_password');
Route::get('logout', 'UserController@logout');
*/

if (\App\Libraries\Utils::isNinja()) {
    Route::post('/signup/register', 'AccountController@doRegister');
    Route::get('/news_feed/{user_type}/{version}/', 'HomeController@newsFeed');
    Route::get('/demo', 'AccountController@demo');
}

Route::group(['middleware' => 'auth'], function() {
    Route::get('dashboard', 'DashboardController@index');
    Route::get('view_archive/{entity_type}/{visible}', 'AccountController@setTrashVisible');
    Route::get('hide_message', 'HomeController@hideMessage');
    Route::get('force_inline_pdf', 'UserController@forcePDFJS');

    Route::get('api/users', array('as'=>'api.users', 'uses'=>'UserController@getDatatable'));
    Route::resource('users', 'UserController');
    Route::post('users/delete', 'UserController@delete');
    Route::get('send_confirmation/{user_id}', 'UserController@sendConfirmation');
    Route::get('restore_user/{user_id}', 'UserController@restoreUser');
    Route::post('users/change_password', 'UserController@changePassword');

    Route::get('api/tokens', array('as'=>'api.tokens', 'uses'=>'TokenController@getDatatable'));
    Route::resource('tokens', 'TokenController');
    Route::post('tokens/delete', 'TokenController@delete');

    Route::get('api/products', array('as'=>'api.products', 'uses'=>'ProductController@getDatatable'));
    Route::resource('products', 'ProductController');
    Route::get('products/{product_id}/archive', 'ProductController@archive');

    Route::get('company/advanced_settings/data_visualizations', 'ReportController@d3');
    Route::get('company/advanced_settings/chart_builder', 'ReportController@report');
    Route::post('company/advanced_settings/chart_builder', 'ReportController@report');

    Route::post('company/cancel_account', 'AccountController@cancelAccount');
    Route::get('account/getSearchData', array('as' => 'getSearchData', 'uses' => 'AccountController@getSearchData'));
    Route::get('company/{section?}/{sub_section?}', 'AccountController@showSection');
    Route::post('company/{section?}/{sub_section?}', 'AccountController@doSection');
    Route::post('user/setTheme', 'UserController@setTheme');
    Route::post('remove_logo', 'AccountController@removeLogo');
    Route::post('account/go_pro', 'AccountController@enableProPlan');

    Route::resource('gateways', 'AccountGatewayController');
    Route::get('api/gateways', array('as'=>'api.gateways', 'uses'=>'AccountGatewayController@getDatatable'));
    Route::post('gateways/delete', 'AccountGatewayController@delete');

    Route::resource('clients', 'ClientController');
    Route::get('api/clients', array('as'=>'api.clients', 'uses'=>'ClientController@getDatatable'));
    Route::get('api/activities/{client_id?}', array('as'=>'api.activities', 'uses'=>'ActivityController@getDatatable'));
    Route::post('clients/bulk', 'ClientController@bulk');

    Route::get('recurring_invoices', 'InvoiceController@recurringIndex');
    Route::get('api/recurring_invoices/{client_id?}', array('as'=>'api.recurring_invoices', 'uses'=>'InvoiceController@getRecurringDatatable'));

    Route::get('invoices/invoice_history/{invoice_id}', 'InvoiceController@invoiceHistory');
    Route::get('quotes/quote_history/{invoice_id}', 'InvoiceController@invoiceHistory');
    
    Route::resource('invoices', 'InvoiceController');
    Route::get('api/invoices/{client_id?}', array('as'=>'api.invoices', 'uses'=>'InvoiceController@getDatatable'));
    Route::get('invoices/create/{client_id?}', 'InvoiceController@create');
    Route::get('invoices/{public_id}/clone', 'InvoiceController@cloneInvoice');
    Route::post('invoices/bulk', 'InvoiceController@bulk');

    Route::get('quotes/create/{client_id?}', 'QuoteController@create');
    Route::get('quotes/{public_id}/clone', 'InvoiceController@cloneInvoice');
    Route::get('quotes/{public_id}/edit', 'InvoiceController@edit');
    Route::put('quotes/{public_id}', 'InvoiceController@update');
    Route::get('quotes/{public_id}', 'InvoiceController@edit');
    Route::post('quotes', 'InvoiceController@store');
    Route::get('quotes', 'QuoteController@index');
    Route::get('api/quotes/{client_id?}', array('as'=>'api.quotes', 'uses'=>'QuoteController@getDatatable'));
    Route::post('quotes/bulk', 'QuoteController@bulk');

    Route::resource('payments', 'PaymentController');
    Route::get('payments/create/{client_id?}/{invoice_id?}', 'PaymentController@create');
    Route::get('api/payments/{client_id?}', array('as'=>'api.payments', 'uses'=>'PaymentController@getDatatable'));
    Route::post('payments/bulk', 'PaymentController@bulk');

    Route::get('credits/{id}/edit', function() {
        return View::make('header');
    });
    Route::resource('credits', 'CreditController');
    Route::get('credits/create/{client_id?}/{invoice_id?}', 'CreditController@create');
    Route::get('api/credits/{client_id?}', array('as'=>'api.credits', 'uses'=>'CreditController@getDatatable'));
    Route::post('credits/bulk', 'CreditController@bulk');

    get('/resend_confirmation', 'AccountController@resendConfirmation');
    //Route::resource('timesheets', 'TimesheetController');
});

// Route group for API
Route::group(['middleware' => 'api', 'prefix' => 'api/v1'], function()
{
    Route::resource('ping', 'ClientApiController@ping');
    Route::resource('clients', 'ClientApiController');
    Route::resource('invoices', 'InvoiceApiController');
    Route::resource('quotes', 'QuoteApiController');
    Route::resource('payments', 'PaymentApiController');
    Route::post('api/hooks', 'IntegrationController@subscribe');
    Route::post('email_invoice', 'InvoiceApiController@emailInvoice');
});

// Redirects for legacy links
Route::get('/rocksteady', function() {
    return Redirect::to(NINJA_WEB_URL, 301);
});
Route::get('/about', function() {
    return Redirect::to(NINJA_WEB_URL, 301);
});
Route::get('/contact', function() {
    return Redirect::to(NINJA_WEB_URL.'/contact', 301);
});
Route::get('/plans', function() {
    return Redirect::to(NINJA_WEB_URL.'/pricing', 301);
});
Route::get('/faq', function() {
    return Redirect::to(NINJA_WEB_URL.'/how-it-works', 301);
});
Route::get('/features', function() {
    return Redirect::to(NINJA_WEB_URL.'/features', 301);
});

app/Models/Invoice.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Invoice extends EntityModel
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $casts = [
        'is_recurring' => 'boolean',
    ];

    public function account()
    {
        return $this->belongsTo('App\Models\Account');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function client()
    {
        return $this->belongsTo('App\Models\Client')->withTrashed();
    }

    public function invoice_items()
    {
        return $this->hasMany('App\Models\InvoiceItem')->orderBy('id');
    }

    public function invoice_status()
    {
        return $this->belongsTo('App\Models\InvoiceStatus');
    }

    public function invoice_design()
    {
        return $this->belongsTo('App\Models\InvoiceDesign');
    }

    public function invitations()
    {
        return $this->hasMany('App\Models\Invitation')->orderBy('invitations.contact_id');
    }

    public function getName()
    {
        return $this->invoice_number;
    }

    public function getFileName()
    {
        $entityType = $this->getEntityType();
        return trans("texts.$entityType") . '_' . $this->invoice_number . '.pdf';
    }

    public function getLink()
    {
        return link_to('invoices/'.$this->public_id, $this->invoice_number);
    }

    public function getEntityType()
    {
        return $this->is_quote ? ENTITY_QUOTE : ENTITY_INVOICE;
    }

    public function isSent()
    {
        return $this->invoice_status_id >= INVOICE_STATUS_SENT;
    }

    public function isViewed()
    {
        return $this->invoice_status_id >= INVOICE_STATUS_VIEWED;
    }

    public function isPaid()
    {
        return $this->invoice_status_id >= INVOICE_STATUS_PAID;
    }

    public function getRequestedAmount()
    {
        return $this->partial > 0 ? $this->partial : $this->balance;
    }

    public function hidePrivateFields()
    {
        $this->setVisible([
            'invoice_number',
            'discount',
            'is_amount_discount',
            'po_number',
            'invoice_date',
            'due_date',
            'terms',
            'invoice_footer',
            'public_notes',
            'amount',
            'balance',
            'invoice_items',
            'client',
            'tax_name',
            'tax_rate',
            'account',
            'invoice_design',
            'invoice_design_id',
            'is_pro',
            'is_quote',
            'custom_value1',
            'custom_value2',
            'custom_taxes1',
            'custom_taxes2',
            'partial',
        ]);

        $this->client->setVisible([
            'name',
            'id_number',
            'vat_number',
            'address1',
            'address2',
            'city',
            'state',
            'postal_code',
            'work_phone',
            'payment_terms',
            'contacts',
            'country',
            'currency_id',
            'custom_value1',
            'custom_value2',
        ]);

        $this->account->setVisible([
            'name',
            'id_number',
            'vat_number',
            'address1',
            'address2',
            'city',
            'state',
            'postal_code',
            'work_phone',
            'work_email',
            'country',
            'currency_id',
            'custom_label1',
            'custom_value1',
            'custom_label2',
            'custom_value2',
            'custom_client_label1',
            'custom_client_label2',
            'primary_color',
            'secondary_color',
            'hide_quantity',
            'hide_paid_to_date',
            'custom_invoice_label1',
            'custom_invoice_label2',
            'pdf_email_attachment',
        ]);

        foreach ($this->invoice_items as $invoiceItem) {
            $invoiceItem->setVisible([
                'product_key',
                'notes',
                'cost',
                'qty',
                'tax_name',
                'tax_rate',
            ]);
        }

        foreach ($this->client->contacts as $contact) {
            $contact->setVisible([
                'first_name',
                'last_name',
                'email',
                'phone',
            ]);
        }

        return $this;
    }

    public function shouldSendToday()
    {
        if (!$this->start_date || strtotime($this->start_date) > strtotime('now')) {
            return false;
        }

        if ($this->end_date && strtotime($this->end_date) < strtotime('now')) {
            return false;
        }

        $dayOfWeekToday = date('w');
        $dayOfWeekStart = date('w', strtotime($this->start_date));

        $dayOfMonthToday = date('j');
        $dayOfMonthStart = date('j', strtotime($this->start_date));

        if (!$this->last_sent_date) {
            return true;
        } else {
            $date1 = new DateTime($this->last_sent_date);
            $date2 = new DateTime();
            $diff = $date2->diff($date1);
            $daysSinceLastSent = $diff->format("%a");
            $monthsSinceLastSent = ($diff->format('%y') * 12) + $diff->format('%m');

            if ($daysSinceLastSent == 0) {
                return false;
            }
        }

        switch ($this->frequency_id) {
            case FREQUENCY_WEEKLY:
                return $daysSinceLastSent >= 7;
            case FREQUENCY_TWO_WEEKS:
                return $daysSinceLastSent >= 14;
            case FREQUENCY_FOUR_WEEKS:
                return $daysSinceLastSent >= 28;
            case FREQUENCY_MONTHLY:
                return $monthsSinceLastSent >= 1;
            case FREQUENCY_THREE_MONTHS:
                return $monthsSinceLastSent >= 3;
            case FREQUENCY_SIX_MONTHS:
                return $monthsSinceLastSent >= 6;
            case FREQUENCY_ANNUALLY:
                return $monthsSinceLastSent >= 12;
            default:
                return false;
        }

        return false;
    }
}

Invoice::created(function ($invoice) {
    $invoice->account->incrementCounter($invoice->invoice_number, $invoice->is_quote, $invoice->recurring_invoice_id);
    Activity::createInvoice($invoice);
});

Invoice::updating(function ($invoice) {
    Activity::updateInvoice($invoice);
});

Invoice::deleting(function ($invoice) {
    Activity::archiveInvoice($invoice);
});

Invoice::restoring(function ($invoice) {
    Activity::restoreInvoice($invoice);
});

resources/views/client.blade.php
<div class="row">
	<div class="col-md-6">

		{!! Former::legend('Organization') !!}
		{!! Former::text('name') !!}
        {!! Former::text('id_number') !!}
        {!! Former::text('vat_number') !!}
		{!! Former::text('work_phone')->label('Phone') !!}
		{!! Former::textarea('notes') !!}

		
		{!! Former::legend('Address') !!}
		{!! Former::text('address1')->label('Street') !!}
		{!! Former::text('address2')->label('Apt/Floor') !!}
		{!! Former::text('city') !!}
		{!! Former::text('state') !!}
		{!! Former::text('postal_code') !!}
		{!! Former::select('country_id')->addOption('','')->label('Country')
			->fromQuery($countries, 'name', 'id') !!}


	</div>
	<div class="col-md-6">

		{!! Former::legend('Contacts') !!}
		<div data-bind='template: { foreach: contacts,
	                            beforeRemove: hideContact,
	                            afterAdd: showContact }'>
			{!! Former::hidden('public_id')->data_bind("value: public_id, valueUpdate: 'afterkeydown'") !!}
			{!! Former::text('first_name')->data_bind("value: first_name, valueUpdate: 'afterkeydown'") !!}
			{!! Former::text('last_name')->data_bind("value: last_name, valueUpdate: 'afterkeydown'") !!}
			{!! Former::text('email')->data_bind("value: email, valueUpdate: 'afterkeydown'") !!}
			{!! Former::text('phone')->data_bind("value: phone, valueUpdate: 'afterkeydown'") !!}

			<div class="form-group">
				<div class="col-lg-8 col-lg-offset-4">
					<span data-bind="visible: $parent.contacts().length > 1">
						{!! link_to('#', 'Remove contact', array('data-bind'=>'click: $parent.removeContact')) !!}
					</span>					
					<span data-bind="visible: $index() === ($parent.contacts().length - 1)" class="pull-right">
						{!! link_to('#', 'Add contact', array('onclick'=>'return addContact()')) !!}
					</span>
				</div>
			</div>

		</div>

	</div>
</div>


{!! Former::hidden('data')->data_bind("value: ko.toJSON(model)") !!}

<script type="text/javascript">

$(function() {
	$('#country_id').combobox();
});

function ContactModel() {
	var self = this;
	self.public_id = ko.observable('');
	self.first_name = ko.observable('');
	self.last_name = ko.observable('');
	self.email = ko.observable('');
	self.phone = ko.observable('');
}

function ContactsModel() {
	var self = this;
	self.contacts = ko.observableArray();
}

@if ($client)
	window.model = ko.mapping.fromJS({!! $client !!});			
@else
	window.model = new ContactsModel();
	addContact();
@endif

model.showContact = function(elem) { if (elem.nodeType === 1) $(elem).hide().slideDown() }
model.hideContact = function(elem) { if (elem.nodeType === 1) $(elem).slideUp(function() { $(elem).remove(); }) }


ko.applyBindings(model);

function addContact() {
	model.contacts.push(new ContactModel());
	return false;
}

model.removeContact = function() {
	model.contacts.remove(this);
}


</script>

resources/views/coming_soon.blade.php
@extends('master')

@section('body')

	<style type="text/css">

		html, body {
		    height: 100%;
		    vertical-align: middle;
		}

		.main_div {
		    width: 500px;
		    height: 200px;
		    
		    position: absolute;
		    top:0;
		    bottom: 0;
		    left: 0;
		    right: 0;

		    font-size: 72px;
		    font-family: arial;
		    color: #CCCCCC;

		    margin: auto;
		}

	</style>

	<div class="main_div">
		coming soon
	</div>

@stop

resources/views/dashboard.blade.php
@extends('header')

@section('content')

<div class="row">
    <div class="col-md-4">  
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{ asset('images/totalincome.png') }}" class="in-image"/>  
                <div class="in-bold">
                    @if (count($paidToDate))
                        @foreach ($paidToDate as $item)
                            {{ Utils::formatMoney($item->value, $item->currency_id) }}<br/>
                        @endforeach
                    @else
                        {{ Utils::formatMoney(0) }}
                    @endif
                </div>
                <div class="in-thin">
                    {{ trans('texts.in_total_revenue') }}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{ asset('images/clients.png') }}" class="in-image"/>  
                <div class="in-bold">
                    {{ $billedClients }}
                </div>
                <div class="in-thin">
                    {{ Utils::pluralize('billed_client', $billedClients) }}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{ asset('images/totalinvoices.png') }}" class="in-image"/>  
                <div class="in-bold">
                    {{ $invoicesSent }}
                </div>
                <div class="in-thin">
                    {{ Utils::pluralize('invoice', $invoicesSent) }} {{ trans('texts.sent') }}
                </div>
            </div>
        </div>
    </div>
</div>


<p>&nbsp;</p>

<div class="row">
    <div class="col-md-6">  
        <div class="panel panel-default dashboard" style="min-height:320px">
            <div class="panel-heading" style="background-color:#0b4d78 !important">
                <h3 class="panel-title in-bold-white">
                    <i class="glyphicon glyphicon-exclamation-sign"></i> {{ trans('texts.notifications') }}
                </h3>
            </div>
            <ul class="panel-body list-group">
                @foreach ($activities as $activity)
                <li class="list-group-item">
                    <span style="color:#888;font-style:italic">{{ Utils::timestampToDateString(strtotime($activity->created_at)) }}:</span>
                    {!! Utils::decodeActivity($activity->message) !!}
                </li>
                @endforeach
            </ul>
        </div>  
    </div>
    <div class="col-md-6">  
        <div class="panel panel-default dashboard" style="min-height:320px">
            <div class="panel-heading" style="background-color:#e37329 !important">
                <h3 class="panel-title in-bold-white">
                    <i class="glyphicon glyphicon-time"></i> {{ trans('texts.invoices_past_due') }}
                </h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <th>{{ trans('texts.invoice_number_short') }}</th>
                        <th>{{ trans('texts.client') }}</th>
                        <th>{{ trans('texts.due_date') }}</th>
                        <th>{{ trans('texts.balance_due') }}</th>
                    </thead>
                    <tbody>
                        @foreach ($pastDue as $invoice)
                        @if (!$invoice->client->trashed())
                        <tr>
                            <td>{{ $invoice->getLink() }}</td>
                            <td>{{ $invoice->client->getDisplayName() }}</td>
                            <td>{{ Utils::fromSqlDate($invoice->due_date) }}</td>
                            <td>{{ Utils::formatMoney($invoice->balance, $invoice->client->currency_id) }}</td>
                        </tr>
                        @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>  
    </div>
</div>

<div class="row">
    <div class="col-md-6">  
        <div class="panel panel-default dashboard" style="min-height:320px;">
            <div class="panel-heading" style="margin:0; background-color: #f5f5f5 !important;">
                <h3 class="panel-title" style="color: black !important">
                    <i class="glyphicon glyphicon-time"></i> {{ trans('texts.upcoming_invoices') }}
                </h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <th>{{ trans('texts.invoice_number_short') }}</th>
                        <th>{{ trans('texts.client') }}</th>
                        <th>{{ trans('texts.due_date') }}</th>
                        <th>{{ trans('texts.balance_due') }}</th>
                    </thead>
                    <tbody>
                        @foreach ($upcoming as $invoice)
                        @if (!$invoice->client->trashed())
                        <tr>
                            <td>{!! $invoice->getLink() !!}</td>
                            <td>{{ $invoice->client->getDisplayName() }}</td>
                            <td>{{ Utils::fromSqlDate($invoice->due_date) }}</td>
                            <td>{{ Utils::formatMoney($invoice->balance, $invoice->client->currency_id) }}</td>
                        </tr>
                        @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="active-clients">      
            <div class="in-bold in-white" style="font-size:42px">{{ $activeClients }}</div>
            <div class="in-thin in-white">{{ Utils::pluralize('active_client', $activeClients) }}</div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="average-invoice">  
            <div><b>{{ trans('texts.average_invoice') }}</b></div>
            <div class="in-bold in-white" style="font-size:42px">
                @foreach ($averageInvoice as $item)
                {{ Utils::formatMoney($item->invoice_avg, $item->currency_id) }}<br/>
                @endforeach
            </div>
        </div>

    </div> 
</div>

@stop

resources/views/datatable.blade.php
<table class="table table-striped {{ $class = str_random(8) }}">
    <colgroup>
        @for ($i = 0; $i < count($columns); $i++)
        <col class="con{{ $i }}" />
        @endfor
    </colgroup>
    <thead>
    <tr>
        @foreach($columns as $i => $c)
        <th align="center" valign="middle" class="head{{ $i }}" 
            @if ($c == 'checkbox')
                style="width:20px"            
            @endif
        >
            @if ($c == 'checkbox' && $hasCheckboxes = true)
                <input type="checkbox" class="selectAll"/>
            @else
                {{ $c }}
            @endif
        </th>
        @endforeach
    </tr>
    </thead>
    <tbody>
    @foreach($data as $d)
    <tr>
        @foreach($d as $dd)
        <td>{{ $dd }}</td>
        @endforeach
    </tr>
    @endforeach
    </tbody>
</table>
<script type="text/javascript">
    jQuery(document).ready(function(){
        // dynamic table
        jQuery('.{{ $class }}').dataTable({
            "fnRowCallback": function(row, data) { 
                if (data[0].indexOf('ENTITY_DELETED') > 0) {
                    $(row).addClass('entityDeleted');
                }
                if (data[0].indexOf('ENTITY_ARCHIVED') > 0) {
                    $(row).addClass('entityArchived');
                }
            },
            "bAutoWidth": false,            
            @if (isset($hasCheckboxes) && $hasCheckboxes)
            'aaSorting': [['1', 'asc']],
            // Disable sorting on the first column
            "aoColumnDefs": [ {
                'bSortable': false,
                'aTargets': [ 0, {{ count($columns) - 1 }} ]                
            } ],
            @endif
            @foreach ($options as $k => $o)
            {!! json_encode($k) !!}: {!! json_encode($o) !!},
            @endforeach
            @foreach ($callbacks as $k => $o)
            {!! json_encode($k) !!}: {!! $o !!},
            @endforeach
            "fnDrawCallback": function(oSettings) {
                if (window.onDatatableReady) {
                    window.onDatatableReady();
                }
            }
        });
    });
</script>

resources/views/error.blade.php
@extends('public.header')

@section('content')

<p>&nbsp;<p>
<p>&nbsp;<p>

<div class="well">
  <div class="container" style="min-height:400px">
	<h3>{{ $error }}</h3>
  Looks like something went wrong.<br/>
  If you'd like help please email us at contact@invoiceninja.com.
</div>
</div>

<p>&nbsp;<p>
<p>&nbsp;<p>


@stop